---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: latest

inputs:
- name: dist-zip-cnb

outputs:
- name: artifactory

caches:
- path: go-module-cache

run:
  path: dist-zip-cnb/ci/package.sh
